#Server
SERVER_PORT: 9001
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: Type Your Email Address Here
EMAIL_PASSWORD: Type Your App Password Here
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}